### ISSUE TITLE
rtop can't be installed via `go get`

### ISSUE THREAD

**Issue by willglynn** [rapidloop/rtop#5]
Steps to reproduce:

    $ go get github.com/rapidloop/rtop

Expected results:

* rtop is installed

Actual results:

    $ go get github.com/rapidloop/rtop
    package github.com/rapidloop/rtop
    	imports github.com/rapidloop/rtop
    	imports github.com/rapidloop/rtop: no buildable Go source files in ~/go/src/github.com/rapidloop/rtop

See also [Organizing Go code](https://blog.golang.org/organizing-go-code). Reorganizing the repo would enable `go get`, permit removal of the `Makefile`, and permit removal of the SSH-related submodule.

**Comment by lafolle** [comment]
+1

**Comment by lafolle** [comment]
To make `rtop` go gettable, I have  
1. Moved all files from `src/` to `rtop`'s root folder
2. Removed `Makefile`
3. Removed `.gitmodules` file  

It will be great if everyone can get the program by just `go get github.com/rapidloop/rtop` rather than cloning then making it.  
Would you like to have pull request for this? You can take a look  at https://github.com/lafolle/rtop/commits/master for commits corresponding to current issue.

**Comment by mdevan** [comment]
Ideally we'd like to shift to [gb](https://github.com/constabulary/gb/blob/master/getting-started.md). With `gb`, the build process will become:

    git clone https://github.com/rapidloop/rtop && cd rtop
    gb vendor golang.org/x/crypto/ssh
    gb build all

We'll probably wait until there is more clarity/standardization around the vendor-plugin.

**Comment by lafolle** [comment]
Cool. `gb` will be great.

Karan

**Comment by mdevan** [comment]
Well, `gb` still seems to be evolving. Until it stabilizes, we'll shift to `go get`. This also allows me to bring in the Windows pull requests less painfully. Commit a072fe2 closes this issue.
